name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v4

      - name: Executar análise com SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.organization=otavio-aramac \
            -Dsonar.projectKey=otavio-aramac-1 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io

  deploy:
    name: Deploy para AWS S3
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código do repositório
        uses: actions/checkout@v4

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Altere para a região correta

      - name: Fazer deploy no S3
        run: aws s3 sync ./ s3://teste-devops-ivory --delete
